# Site settings
title: Board Gamers of Hyderabad
email: boardgamersofhyderabad@gmail.com
description: Official Website for Board Gamers of Hyderabad
opening_line: Welcome to most happening club in Hyderabad
author: Himanshu
version: v1

#Social Media Profile
social_media:
 - name: facebook
   link:
   
 - name: twitter
   link:
   
 - name: whatsapp
   link:
#end

# Build settings
markdown: kramdown

# Global nav settings
home: '/'
about-us: '#about-us'
our-activities: '#our-activities'
code-of-conduct: '/code-of-conduct'
find-us: '#find-us'