# Site settings
title: Board Gamers of Hyderabad
email: boardgamersofhyderabad@gmail.com
description: Official Website for Board Gamers of Hyderabad
baseurl: ""
url: ""

twitter_username:
github_username: 

# Build settings
markdown: kramdown

# Global nav settings
home: '/'
about-us: '#about-us'
our-activities: '#our-activities'
code-of-conduct: '/code-of-conduct'
find-us: '#find-us'

