# Site settings
title: Board Gamers of Hyderabad
email: boardgamersofhyderabad@gmail.com
description: Official Website for Board Gamers of Hyderabad
author: Himanshu
version: v1
header_title: BGH
fonts:
  heading: Oswald
  content: Roboto
defaults:
- scope:
    path: eventImages
  values:
    image: true
socialLinks:
  Facebook: https://www.facebook.com
  Instagram: https://www.facebook.com
  WhatsApp: https://www.facebook.com
  Meetup: https://www.facebook.com
markdown: kramdown