# Site settings
---
title: Himanshu C Reddy | Marketer & Digital Strategist
description: Meticulous and a creative marketer with 7+ years of experience in digital marketing & strategy in fast-paced start-ups as well as process-oriented enterprises. I ensure businesses goals meet customers expectation and help both thrive in the digital ecosystem.
cdn: https://cdn.jsdelivr.net/gh/hymnzzy/hymnzzy.github.io
index:
  intro:
    name: Himanshu
  about:
    years: 7
    expertise:
      - name: Digital Marketing
        level: 95%
      - name: Branding
        level: 90%
      - name: Digital Transformation
        level: 85%
      - name: Program Management
        level: 80%
      - name: Product Management
        level: 75%
      - name: Offline Marketing
        level: 60%
    skills:
      - SEO
      - SEM
      - SMM
      - Retargeting
      - Lead Management
      - E-Commerce
      - AIDA Funnel
      - Marketing Research
      - Strategic Planning
      - SWOT Analysis
      - Data Modelling
      - Agency Management
      - Powershell
      - Process Automation
      - HTML / CSS3 / JS
      - Photoshop
      - Modular Programming


#Social Media Profile


# Build settings
markdown: kramdown